spring.application.name=codingplatform
spring.datasource.url=jdbc:mysql://localhost:3306/coding_platform
spring.datasource.username=root
spring.datasource.password=Ajay.1@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true